### ISSUE TITLE
Useless signing?

### ISSUE THREAD

**Issue by tenbits** [tj/node-cookie-signature#15]
Hi Team, 
at the [#L42](https://github.com/visionmedia/node-cookie-signature/blob/master/index.js#L42) `val` and `mac` are already equal strings _(in case [signing](https://github.com/visionmedia/node-cookie-signature/blob/master/index.js#L40) was successful)_, should they be signed anyway before equallity check? 
Cheers, Alex

**Comment by dminkovsky** [comment]
Sorry to keep on the bike shed, but why not just use https://github.com/SalesforceEng/buffer-equal-constant-time?—either the module or just copy/paste the code.

**Comment by dminkovsky** [comment]
I mean why use `sha1`? Is the implementation of that function always going to be constant time? (sorry, I don't know how `sha1` is implemented).

Anyway, a loop seems much simpler: https://github.com/SalesforceEng/buffer-equal-constant-time/blob/a48282ae383e6728d1dea74e2de43e8a8a434326/index.js#L8-L34. Pretty standard stuff, have seen it elsewhere: https://gist.github.com/jtan189/3804290#file-javapasswordsecurity-java-L103-L109.

**Comment by tenbits** [comment]
`sha1` is not about the constant time, but on the contrary - it ensures randomness.

**Comment by jtlapp** [comment]
Do we know that the faster CRC32 wouldn't suffice? It's less random than SHA1, but how much information can be gleaned from a single CRC byte? I'm just concerned that we may be unnecessarily eating clock cycles.

**Comment by jtlapp** [comment]
If the purpose is to prevent timing attacks, why aren't you using a constant time comparison? SHA1 is computationally expensive, and you are doing it twice on each request for a signed cookie. I've been testing XOR comparisons with benchmark.js and find them to be constant time on my machine.

Moreover, by comparing the cryptographically random signatures instead of SHA1 hashes, you are forcing the attacker to find collisions in 256 bits instead of only 160. It seems that a constant-time comparison is not only faster, but more secure.

Do constant-time comparisons have a machine-dependence that makes them unreliable? What's the deal?

**Comment by jtlapp** [comment]
(The reason I ask is that I would like to verify session ID signatures as a means for reducing the impact of DDoS attacks. I'll confirm the ID too, but that may require hitting the database. I want to keep the cost of each invalid request to a minimum by only hitting the DB if the signature verifies. I don't need the signature otherwise. But if adding the signature is itself costly, it's not clear how much benefit I gain.)
