### ISSUE TITLE
Snyk has (incorrectly?) marked versions <1.1.0 as vulunerable

### ISSUE THREAD

**Issue by dougwilson** [tj/node-cookie-signature#27]
Is it possible to revisit my PR https://github.com/tj/node-cookie-signature/pull/25 ? This is affecting Express and showing that there is a vulnerability, and a lot of folks have their deployment process fail on a vulnerability from Snyk: https://snyk.io/vuln/npm:cookie-signature:20180111

I though @natevw we discussed this and that prior versions were not vulnerable? Has something changed here? Also cc @jodevsa @drewjenkins @wesleytodd

**Comment by natevw** [comment]
Nothing has changed, I will try contact Snyk to figure out if there's a way to fix their database.

**Comment by natevw** [comment]
Update: I emailed their contact@ and support@ and for now will refrain from also spamming their report@ since I imagine it's not a huge company.

It looks like [their vulnerability database](https://github.com/snyk/vulnerabilitydb) is on Github but I'm not finding the incorrect report.

They do have
https://github.com/snyk/vulnerabilitydb/blob/316f48af9a031fd2cc90eeb61907e77511ee3f0f/data/npm/cookie-signature/20160804/README.md which is correct, but not the 20180111 report so I can't simply add a pull request. I may file an issue there though.

**Comment by wesleytodd** [comment]
Twitter to the rescue: https://twitter.com/anna_debenham/status/971092247759523841

**Comment by grnd** [comment]
Thank you for bringing this to our attention. We just issued a fix. Sorry for the inconvenience caused.

**Comment by natevw** [comment]
@dougwilson What's next here?

I should probably a note to the README saying something like:

> There are two versions of the library available for use:
>
> * 1.1.1 relies on features of node.js version 6.6.0 and above
> * 1.0.6 builds in similar functionality but supports older node.js engines
>
> Continued support for the 1.0.x branch is planned should maintenance be found necessary. (Do **not** use versions prior to 1.0.4 as they were [vulnerable to timing attacks](https://snyk.io/vuln/npm:cookie-signature:20160804).)

(The version will be bumped to 1.1.1 only so that I can publish the updated readme on NPM… see http://blog.npmjs.org/post/77758351673/no-more-npm-publish-f for background.)

---

That seems the simplest plan. I'd also be willing to extend this to three versions where 1.2 would be PR #25, and 1.3 would be 1.1 + #26 improvements:

> * 1.3 has no dependencies but relies on features of node.js version 6.6.0 and above
> * 1.2 works on older node using an external dependency
> * 1.0.6 has no dependencies and works on older node

Upsides: gets 1.1 release out of the picture, provides an option for everyone, leaves the simplest/cleanest version

Downsides: three versions to maintain, three versions to audit, and Express would still be using an "older" version. We're practically publishing three different packages (`cookie-signature`, `cookie-signature-leftpad`, `cookie-signature-classic`) but through versioning.

Feedback appreciated all around!

**Comment by wesleytodd** [comment]
As I am not super familiar with the history of this project I cannot day with authority, but IMO the major problem is dropping support for node versions is a breaking change, and should NEVER happen in a minor point release.  

So if you plan on dropping support for `<6.6.0`, then you need to go to `2.0.0` (and apparently should have published `1.1.0` as `2`).  So whichever path forward is chosen, it should take this into account.

**Comment by dougwilson** [comment]
Hi everyone, sorry I didn't follow up here quickly; time flies. Yes, there are debates on when to bump what parts of a semver especially around what you think your actual API interface is (does it include the version of your dependent runtime or not?). I don't think we need to really debate that here, and is just why I choose to pin versions of module because everyone has different opinions.

I'm fine with the 1.0 vs 1.1 split here, and am not asking anything to change. I was just confused on how a version got marked vulnerable even though a week prior I spoke with @natevw here about this very issue and (even in a public forum) it was sated that 1.1.0 doesn't contain a security fix. How exactly this got listed in a vulnerability registry, especially when it seems the author of the module in question wasn't aware of the listing is beyond me; something smells broken here.

**Comment by camsjams** [comment]
Thanks for the hardwork - this is also still considered open in https://www.sourceclear.com/vulnerability-database/vulnerabilities/5730

**Comment by wesleytodd** [comment]
Are there tools which detect reports from this source?  I have never heard of it, so if you have can you take up the job of getting that removed?

**Comment by camsjams** [comment]
@wesleytodd I'd be happy to, and have sent over an email today to their support. Just wanted it recorded - hopefully the sourceclear issue will be updated in due time.

**Comment by VanessaHenderson** [comment]
Hi there!
I'm Vanessa from SourceClear's support team. Thanks for reporting this issue to us. I've reviewed the evidence given and the conversations and agree that this was a false positive in our database. I've removed the artifact. Once again, thanks for pointing this out!

**Comment by natevw** [comment]
Thanks @VanessaHenderson for fixing this!
