### ISSUE TITLE
Compatibility with older Node versions

### ISSUE THREAD

**Issue by FadhiliNjagi** [tj/node-cookie-signature#45]
Could you use the `buffer-from` ponyfill so the library becomes compatible with older Node versions (from node 0.10)?

**Comment by natevw** [comment]
Basically all the improvements to this library in recent years have been related to improvements to Node.js also. So it's easier to just revert the `Buffer.from` and `crypto.timingSafeEqual` changes since those changes were just to use newer Node nicer.

Which is to say, if you need compatibility for older Node.js, you can use an older version of this library!

Does `npm install --save cookie-signature@1.0.6` work for you on node v0.10?

**Comment by FadhiliNjagi** [comment]
Yeah, it does. Though it only accepts string secrets. I wanted to use Buffers.

**Comment by natevw** [comment]
I made a branch called `v1.0.x` if you do want to propose a PR into that branch with a fix so that you can use `Buffer` secrets there?

**Comment by natevw** [comment]
Now published as `cookie-signature@1.0.7` — thanks again!
