### ISSUE TITLE
Having 1.2.1 updates tells me 1.0.7

### ISSUE THREAD

**Issue by NormandoHall** [tj/node-cookie-signature#48]
Hello.

After a few weeks ago, when I do `npm outdated` get me `1.0.7` as latest package, but I have `1.2.1`

`package.json`

```json
...
"cookie-signature": "^1.2.1",
...
```

I think it is no correct

**Comment by natevw** [comment]
Uh-oh, I was worried about that but hoped that semver would take care of it! Thanks for reporting this.

The situation is that:

* the actual best/newest/latest version is still `1.2.1` as you have
* but the most recent (in time) release was `1.0.7` intended only to backport some current features to older node.js

I will have to learn more about how `npm` works and why it does based on date rather than semver. Because even at <https://www.npmjs.com/package/cookie-signature> the **wrong** version is showing now!

<img width="175" alt="Clipped screenshot from npmjs website showing Version 1.0.7 badge for this library" src="https://user-images.githubusercontent.com/265902/233456360-431352bf-5649-40c9-a160-0765e2b4870d.png">

Maybe for now I will just publish a `1.2.2` update with no real changes just to make it recommend the right version by default.

**Comment by dougwilson** [comment]
`npm dist-tag add cookie-signature@1.2.1 latest`

**Comment by natevw** [comment]
> `npm dist-tag add cookie-signature@1.2.1 latest`

Much better, thank you very much!! Tagging the existing intended package as `latest` worked and so I think this issue should be resolved now.
